## product data

In [97]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import linear_kernel
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import normalize
from sklearn.metrics.pairwise import cosine_similarity

In [99]:
data_path = "/kaggle/input/face-clean-ecomer"

In [101]:
df_product = pd.read_csv(f"{data_path}/data_product_combine.csv")
display(df_product)

,avg_star,num_sold_time,price,product_id,product_name,brand,origin,type,skin_kind,num_rating,processed_description,image_path,popularity_score,combined_text
0,4.8,185700,99000.0,0,Sữa rửa mặt Simple lành tính sạch thoáng - cho...,simple,no_origin,no_type,no_skin,66840,ưu_điểm nổi_trội sữa rửa mặt simple lành_tính ...,111138057_8587034871.jpg,0.992000,Sữa rửa mặt Simple lành tính sạch thoáng - cho...
1,4.8,102600,99000.0,1,Sữa rửa mặt Simple giúp kiềm dầu và ngừa mụn h...,simple,no_origin,no_type,no_skin,36552,ưu_điểm nổi_trội sữa rửa mặt simple giúp kiềm ...,111138057_8287055694.jpg,0.632309,Sữa rửa mặt Simple giúp kiềm dầu và ngừa mụn h...
2,4.9,8100,244000.0,2,Sữa rửa mặt nam 30Shine phân phối chính hãng S...,Skin&Dr\t,Việt Nam,dạng kem,no_skin,2644,sữa rửa mặt nam skin dr tràm trà 80 g cho da m...,21080428_9335942418.mp4,0.229677,Sữa rửa mặt nam 30Shine phân phối chính hãng S...
3,4.9,3600,119000.0,3,Sữa rửa mặt nam RHYS MAN Rhys Coconut Fresh hư...,RHYS MAN,Việt Nam,dạng sánh,Da hỗn hợp,180,chính hãng sữa rửa mặt nam rhys man rhys cocon...,758111427_19601743242.mp4,0.206501,Sữa rửa mặt nam RHYS MAN Rhys Coconut Fresh hư...
4,4.8,26300,9900.0,4,Sữa Rửa Mặt Senana Lấy Sạch Bụi Bẩn Giúp Da T...,no_brand,no_origin,no_type,no_skin,6312,sỉ tốt 13 k c bao giá sl toàn_quốc ngại j khôn...,107632788_3330988133.jpg,0.291143,Sữa Rửa Mặt Senana Lấy Sạch Bụi Bẩn Giúp Da T...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2239,5.0,872,82000.0,2239,Sữa rửa mặt Kose Softymo Nhật Bản 220g,KOSÉ,no_origin,no_type,no_skin,270,sữa rửa mặt kose nhật bản best của best luôn a...,294293046_5445658669.jpg,0.203560,Sữa rửa mặt Kose Softymo Nhật Bản 220g [BRAND]...
2240,5.0,43,205000.0,2240,Sữa rửa mặt La Roche-Posay Effaclar chuyên dàn...,La Roche-Posay,Pháp,dạng gel,"Da mụn trứng cá, Da hỗn hợp, Dầu, Nhạy cảm",12,sữa rửa mặt la efaclar foaming gel sẽ giúp ngă...,97333460_10761076591.jpg,0.200170,Sữa rửa mặt La Roche-Posay Effaclar chuyên dàn...
2241,4.9,823,75000.0,2241,Sữa rửa mặt Kose Softymo Nhật Bản 220g,no_brand,no_origin,no_type,no_skin,218,sữa rửa mặt kose softymo là sản_phẩm sữa rửa m...,315629668_3455178555.jpg,0.199194,Sữa rửa mặt Kose Softymo Nhật Bản 220g [BRAND]...
2242,5.0,1000,79000.0,2242,Sữa Rửa Mặt Làm Sáng Da Reihaku Hatomugi Facia...,HATOMUGI,Nhật Bản,no_type,no_skin,439,thương_hiệu reihaku hatomugi xuất_xứ nhật bản ...,258099521_6677227750.jpg,0.204663,Sữa Rửa Mặt Làm Sáng Da Reihaku Hatomugi Facia...
2243,4.9,186,30000.0,2243,Sữa Rửa Mặt Bơ Aron Thái Lan 210g dưỡng ẩm và ...,no_brand,no_origin,no_type,no_skin,35,sữa rửa mặt bơ aron thái lan 210 g dưỡng ẩm và...,40662254_15079529213.jpg,0.196658,Sữa Rửa Mặt Bơ Aron Thái Lan 210g dưỡng ẩm và ...

## TF-IDF

**TF-IDF** (viết tắt của Term Frequency-Inverse Document Frequency) là một kỹ thuật thống kê dạng số dùng để đánh giá tầm quan trọng của một từ trong một tài liệu hoặc một văn bản trong một tập hợp các tài liệu (corpus). Giá trị TF-IDF càng cao thì độ quan trọng của từ đó càng lớn trong tài liệu và trong cả tập hợp tài liệu.

In [102]:
tf = TfidfVectorizer(analyzer="word")
tfidf_matrix = tf.fit_transform(df_product["combined_text"])
tfidf_matrix  # la sparse matrix
tfidf_matrix.shape

(2244, 10604)

In [103]:
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
cosine_sim

array([[1.        , 0.86255579, 0.16297268, ..., 0.19061156, 0.18217464,
        0.18487124],
       [0.86255579, 1.        , 0.17539769, ..., 0.20054225, 0.19160009,
        0.17756289],
       [0.16297268, 0.17539769, 1.        , ..., 0.15743214, 0.15593822,
        0.13342997],
       ...,
       [0.19061156, 0.20054225, 0.15743214, ..., 1.        , 0.23010215,
        0.23670292],
       [0.18217464, 0.19160009, 0.15593822, ..., 0.23010215, 1.        ,
        0.17223299],
       [0.18487124, 0.17756289, 0.13342997, ..., 0.23670292, 0.17223299,
        1.        ]])

In [104]:
cosine_sim.shape

(2244, 2244)

## AITeamVN/Vietnamese_Embedding

In [1]:
import torch
from sentence_transformers import SentenceTransformer

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

/home/daniel/anaconda3/envs/face_clean/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Using device: cuda

In [106]:
text_combine = df_product["combined_text"].values.tolist()

In [2]:
# Tải mô hình Vietnamese_Embedding
local_model_path = "/home/daniel/Desktop/ecom-facecare-recommender/models"
vietnamese_embedding = SentenceTransformer(
    "AITeamVN/Vietnamese_Embedding", cache_folder=local_model_path
)
vietnamese_embedding.max_seq_length = 2048
vietnamese_embedding.to(device)

SentenceTransformer(
  (0): Transformer({'max_seq_length': 2048, 'do_lower_case': False}) with Transformer model: XLMRobertaModel
  (1): Pooling({'word_embedding_dimension': 1024, 'pooling_mode_cls_token': True, 'pooling_mode_mean_tokens': False, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)

In [108]:
# Encode dữ liệu mô tả sản phẩm
encoded_descriptions = vietnamese_embedding.encode(
    text_combine,
    show_progress_bar=True,
    batch_size=64,
    convert_to_numpy=True,
    device=device,
)

# Lu lai ket qua
np.save("/kaggle/working/vietnamese_embedding.npy", encoded_descriptions)

Batches:   0%|          | 0/36 [00:00<?, ?it/s]

In [ ]:
# vietnamese_embedding.to("cpu")
torch.cuda.empty_cache()
exit()

:

In [ ]:
vie_embed = np.load("../embeddings/vietnamese_embedding.npy")
vie_embed_cosine_sim = linear_kernel(vie_embed, vie_embed)
vie_embed_cosine_sim

array([[0.9999999 , 0.77119076, 0.42959484, ..., 0.48645723, 0.50598043,
        0.47021967],
       [0.77119076, 1.        , 0.44234556, ..., 0.5088982 , 0.47064126,
        0.47992572],
       [0.42959484, 0.44234556, 1.        , ..., 0.39891997, 0.38103268,
        0.392535  ],
       ...,
       [0.48645723, 0.5088982 , 0.39891997, ..., 0.99999964, 0.52953607,
        0.48498675],
       [0.50598043, 0.47064126, 0.38103268, ..., 0.52953607, 1.        ,
        0.56553054],
       [0.47021967, 0.47992572, 0.392535  , ..., 0.48498675, 0.56553054,
        1.0000004 ]], dtype=float32)

In [111]:
# Tải mô hình Vietnamese_bi_encoder
vietnamese_bi_encoder = SentenceTransformer(
    "bkai-foundation-models/vietnamese-bi-encoder"
)
vietnamese_bi_encoder.max_seq_length = 256
vietnamese_bi_encoder.to(device)

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False}) with Transformer model: RobertaModel
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
)

In [112]:
# Encode dữ liệu mô tả sản phẩm
vie_bi_encode = vietnamese_bi_encoder.encode(
    text_combine,
    show_progress_bar=True,
    batch_size=64,
    convert_to_numpy=True,
    device=device,
)

# Lu lai ket qua
np.save("vie_bi_encode_embedding.npy", vie_bi_encode)

# giai phong bo nho Vram
vietnamese_bi_encoder.to("cpu")
torch.cuda.empty_cache()

Batches:   0%|          | 0/36 [00:00<?, ?it/s]

In [ ]:
vie_bi_encoder_embed = np.load("../embeddings/vie_bi_encode_embedding.npy")
vie_bi_encoder_cosine_sim = linear_kernel(vie_bi_encoder_embed, vie_bi_encoder_embed)
print(f"Shape of cosine similarity matrix: {vie_bi_encoder_cosine_sim.shape}")
vie_bi_encoder_cosine_sim

Shape of cosine similarity matrix: (2244, 2244)

array([[27.470388, 21.772205, 10.865797, ..., 13.933599,  8.992716,
         9.962082],
       [21.772205, 30.993454, 15.172373, ..., 14.56547 , 10.295783,
        11.08555 ],
       [10.865797, 15.172373, 30.132406, ..., 10.320612,  9.998255,
         9.431982],
       ...,
       [13.933599, 14.56547 , 10.320612, ..., 31.113583, 13.752178,
        10.318734],
       [ 8.992716, 10.295783,  9.998255, ..., 13.752178, 31.74048 ,
        13.593079],
       [ 9.962082, 11.08555 ,  9.431982, ..., 10.318734, 13.593079,
        29.83865 ]], dtype=float32)

### Information Retrieval

#### Leverage Text Embeddings for Information Retrieval

In [132]:
from sklearn.preprocessing import normalize
from sklearn.metrics.pairwise import cosine_similarity


def search_products_embedding(query, top_n=10, model_name="bi-encoder"):
    """
    Tìm kiếm sản phẩm dựa trên truy vấn văn bản sử dụng embedding model

    Args:
        query (str): Câu truy vấn tìm kiếm
        top_n (int): Số lượng kết quả trả về
        model_name (str): Tên model embedding ("bi-encoder" hoặc "vie-embed")

    Returns:
        list: Danh sách sản phẩm phù hợp nhất
    """
    # Load model và embedding sản phẩm
    if model_name == "bi-encoder":
        vietnamese_model = vietnamese_bi_encoder
        max_seq_length = 256
        product_embeddings = (
            vie_bi_encoder_embed  # Đây là ma trận (n_sản_phẩm, embedding_dim)
        )
    else:  # "vie-embed"
        vietnamese_model = vietnamese_embedding
        max_seq_length = 2048
        product_embeddings = vie_embed

    # Encode câu truy vấn
    query_embedding = vietnamese_model.encode([query], convert_to_numpy=True)
    # query_embedding = normalize(query_embedding)

    # Normalize toàn bộ embedding sản phẩm (chỉ cần làm 1 lần nếu chưa)
    # product_embeddings = normalize(product_embeddings)

    # Tính cosine similarity giữa query và tất cả sản phẩm
    cosine_similarities = cosine_similarity(
        query_embedding, product_embeddings
    ).flatten()

    # Lấy top N kết quả giống nhất
    top_indices = cosine_similarities.argsort()[::-1][:top_n]

    # Trả về các sản phẩm tương ứng (df_product phải có sẵn, chỉ số trùng với embedding)
    return df_product.iloc[top_indices]

In [133]:
query = "Sữa rửa mặt Pháp dưỡng ẩm."
result_search = search_products_embedding(
    query, top_n=10, model_name="vietnamese_embedding"
)
print(f"Kết quả tìm kiếm cho '{query}':")
display(result_search["origin"])

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Kết quả tìm kiếm cho 'Sữa rửa mặt Pháp dưỡng ẩm.':

2044         Pháp
664     no_origin
1106       Isarel
1542     Việt Nam
970     no_origin
692      Việt Nam
1144    no_origin
1872           Mỹ
1865    no_origin
433     no_origin
Name: origin, dtype: object

In [134]:
query = "Sữa rửa mặt Pháp dưỡng ẩm."
result_search = search_products_embedding(query, top_n=10, model_name="bi-encoder")
print(f"Kết quả tìm kiếm cho '{query}':")
display(result_search["origin"])

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Kết quả tìm kiếm cho 'Sữa rửa mặt Pháp dưỡng ẩm.':

210      no_origin
2209          Pháp
1333    Trung Quốc
934           Pháp
1852      Hàn Quốc
1990          Pháp
749      no_origin
1122     no_origin
460      no_origin
1452     no_origin
Name: origin, dtype: object

In [127]:
query = "Sữa rửa mặt RHYS MAN"
result_search = search_products_embedding(
    query, top_n=10, model_name="vietnamese_embedding"
)
print(f"Kết quả tìm kiếm cho '{query}':")
display(result_search)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Kết quả tìm kiếm cho 'Sữa rửa mặt RHYS MAN':

,avg_star,num_sold_time,price,product_id,product_name,brand,origin,type,skin_kind,num_rating,processed_description,image_path,popularity_score,combined_text
308,4.9,1400,159000.0,308,Sữa rửa mặt nam RHYS MAN hương dừa Rhys Coconu...,RHYS MAN,Việt Nam,dạng sánh,"Da hỗn hợp, Khô, Dầu",43,sữa rửa mặt nam rhys man hương dừa rhys coconu...,293694567_12459206331.mp4,0.199963,Sữa rửa mặt nam RHYS MAN hương dừa Rhys Coconu...
101,4.9,2100,99000.0,101,Sữa rửa mặt nam RHYS MAN hương dừa thơm mát Rh...,RHYS MAN,Việt Nam,dạng sánh,Các loại da,348,sữa rửa mặt nam rhys man ngừa mụn rhys coconut...,293944676_12885937488.mp4,0.203216,Sữa rửa mặt nam RHYS MAN hương dừa thơm mát Rh...
54,4.9,1700,99000.0,54,Sữa rửa mặt nam RHYS MAN hương dừa Rhys Coconu...,RHYS MAN,Việt Nam,dạng sánh,"Da hỗn hợp, Da mụn trứng cá, Khô, Dầu",231,sữa rửa mặt nam rhys man ngừa mụn rhys coconut...,294041670_17331679811.mp4,0.201614,Sữa rửa mặt nam RHYS MAN hương dừa Rhys Coconu...
3,4.9,3600,119000.0,3,Sữa rửa mặt nam RHYS MAN Rhys Coconut Fresh hư...,RHYS MAN,Việt Nam,dạng sánh,Da hỗn hợp,180,chính hãng sữa rửa mặt nam rhys man rhys cocon...,758111427_19601743242.mp4,0.206501,Sữa rửa mặt nam RHYS MAN Rhys Coconut Fresh hư...
309,4.9,3800,389000.0,309,Bộ Quà Tặng Nam - Sữa tắm gội nam 350 ml & Sữa...,RHYS MAN,Việt Nam,dạng sánh,no_skin,266,chính hãng combo sữa tắm_gội nam 350 ml sữa rử...,758111427_16765092719.mp4,0.207425,Bộ Quà Tặng Nam - Sữa tắm gội nam 350 ml & Sữa...
1447,5.0,484,107500.0,1447,Sữa Rửa Mặt GẠO Rice Mousse 150ml / 100ml THE ...,The Faceshop,Hàn Quốc,dạng kem,no_skin,110,công_dụng của sữa rửa mặthe face_shop rice wat...,67707436_6712187900.mp4,0.201797,Sữa Rửa Mặt GẠO Rice Mousse 150ml / 100ml THE ...
1451,5.0,14,599000.0,1451,Sữa Rửa mặt Christina BIOPHYTO MILD CLEANER,no_brand,Isarel,dạng sánh,Mọi loại da,2,dùng srm dòng biophyto xong cảm_giác da rất sạ...,251801855_12201277503.jpg,0.200047,Sữa Rửa mặt Christina BIOPHYTO MILD CLEANER [B...
1020,4.9,402,22000.0,1020,sữa rửa mặt nhân sâm hàn quốc,no_brand,no_origin,dạng lỏng,Da hỗn hợp,72,rose sữa rửa mặt nhân_sâm korea red ginseng fo...,120827064_4759376783.jpg,0.197406,sữa rửa mặt nhân sâm hàn quốc [BRAND] no_brand...
1547,4.9,427,57000.0,1547,Sữa rữa mặt nhân sâm Hàn Quốc chính hãng,no_brand,Hàn Quốc,dạng kem,Mọi loại da,108,sữa rữa mặt nhân_sâm đỏ hàng xịn smiling_face_...,26320661_1436341173.jpg,0.197634,Sữa rữa mặt nhân sâm Hàn Quốc chính hãng [BRAN...
1033,4.8,505,28000.0,1033,Sữa Rửa Mặt Hồng Sâm Đỏ My Gold Hàn Quốc,no_brand,no_origin,no_type,no_skin,71,sữa rửa mặt sạch sâu và trắng da hồng sâm đỏ m...,163266766_6134797406.jpg,0.193678,Sữa Rửa Mặt Hồng Sâm Đỏ My Gold Hàn Quốc [BRAN...

In [128]:
query = "Sữa rửa mặt RHYS MAN"
result_search = search_products_embedding(query, top_n=10, model_name="bi-encoder")
print(f"Kết quả tìm kiếm cho '{query}':")
display(result_search)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Kết quả tìm kiếm cho 'Sữa rửa mặt RHYS MAN':

,avg_star,num_sold_time,price,product_id,product_name,brand,origin,type,skin_kind,num_rating,processed_description,image_path,popularity_score,combined_text
308,4.9,1400,159000.0,308,Sữa rửa mặt nam RHYS MAN hương dừa Rhys Coconu...,RHYS MAN,Việt Nam,dạng sánh,"Da hỗn hợp, Khô, Dầu",43,sữa rửa mặt nam rhys man hương dừa rhys coconu...,293694567_12459206331.mp4,0.199963,Sữa rửa mặt nam RHYS MAN hương dừa Rhys Coconu...
101,4.9,2100,99000.0,101,Sữa rửa mặt nam RHYS MAN hương dừa thơm mát Rh...,RHYS MAN,Việt Nam,dạng sánh,Các loại da,348,sữa rửa mặt nam rhys man ngừa mụn rhys coconut...,293944676_12885937488.mp4,0.203216,Sữa rửa mặt nam RHYS MAN hương dừa thơm mát Rh...
54,4.9,1700,99000.0,54,Sữa rửa mặt nam RHYS MAN hương dừa Rhys Coconu...,RHYS MAN,Việt Nam,dạng sánh,"Da hỗn hợp, Da mụn trứng cá, Khô, Dầu",231,sữa rửa mặt nam rhys man ngừa mụn rhys coconut...,294041670_17331679811.mp4,0.201614,Sữa rửa mặt nam RHYS MAN hương dừa Rhys Coconu...
3,4.9,3600,119000.0,3,Sữa rửa mặt nam RHYS MAN Rhys Coconut Fresh hư...,RHYS MAN,Việt Nam,dạng sánh,Da hỗn hợp,180,chính hãng sữa rửa mặt nam rhys man rhys cocon...,758111427_19601743242.mp4,0.206501,Sữa rửa mặt nam RHYS MAN Rhys Coconut Fresh hư...
1388,5.0,172,260000.0,1388,Sữa rửa mặt Huxley,Huxley (),Hàn Quốc,no_type,no_skin,40,sữa rửa mặt huxley cactus 20 ml đã dùng huxley...,5194200_4544597375.jpg,0.200643,Sữa rửa mặt Huxley [BRAND] Huxley () [ORIGIN] ...
961,5.0,113,235000.0,961,Sữa rửa mặt BEAUTY OF JOSEON Green Plum Refres...,no_brand,no_origin,no_type,no_skin,39,đã về hàng sau hơn 2 tháng thumbs_up_light_ski...,4264454_12465581916.jpg,0.200479,Sữa rửa mặt BEAUTY OF JOSEON Green Plum Refres...
1398,5.0,540,699000.0,1398,[Made in USA] Fresh Sữa Rửa Mặt (SRM) Cho Da N...,Fresh,no_origin,no_type,no_skin,172,person_tipping_hand_medium light_skin_tone fre...,47230535_1485193125.jpg,0.202226,[Made in USA] Fresh Sữa Rửa Mặt (SRM) Cho Da N...
1489,5.0,69,53500.0,1489,sữa rửa mặt rickin hàng chuẩn,no_brand,Nhật Bản,dạng kem,no_skin,4,sữa rửa mặt rick skin chưa từng thất_bại face_...,594969517_12268220289.jpg,0.200204,sữa rửa mặt rickin hàng chuẩn [BRAND] no_brand...
1603,5.0,341,285000.0,1603,Sữa rửa mặt ngải cứu Bring Green Artemisia PH ...,BRING GREEN,Hàn Quốc,dạng kem,Mọi loại da,110,1 thông_tin xuất_xứ sp red_triangle_pointed_up...,7962964_4021268132.jpg,0.201412,Sữa rửa mặt ngải cứu Bring Green Artemisia PH ...
1828,5.0,4,185000.0,1828,SỮA RỬA MẶT ROUNDLAB,ROUND LAB,Hàn Quốc,no_type,no_skin,1,minhf si_mê roundlab từ hồi dùng toner của hãn...,728266995_17055832109.jpg,0.200015,SỮA RỬA MẶT ROUNDLAB [BRAND] ROUND LAB [ORIGIN...

In [129]:
query = "Sữa rửa mặt kiềm dầu cho nam"
result_search = search_products_embedding(
    query, top_n=10, model_name="vietnamese_embedding"
)
print(f"Kết quả tìm kiếm cho '{query}':")
display(result_search)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Kết quả tìm kiếm cho 'Sữa rửa mặt kiềm dầu cho nam':

,avg_star,num_sold_time,price,product_id,product_name,brand,origin,type,skin_kind,num_rating,processed_description,image_path,popularity_score,combined_text
1887,4.8,125,15500.0,1887,"Sữa Rửa Mặt Kiềm Dầu, Sữa Rửa Mặt Tạo Bọt Cho ...",no_brand,Trung Quốc,dạng lỏng,"Da mụn trứng cá, Lão hóa, Mọi loại da, Da hỗn ...",46,sữa rửa mặt đầu cọ silicon sạch gấp 10 lần rửa...,419934030_13231978624.jpg,0.192543,"Sữa Rửa Mặt Kiềm Dầu, Sữa Rửa Mặt Tạo Bọt Cho ..."
885,5.0,13,51000.0,885,"Sửa Rửa Mặt, Bột Rửa Mặt Cho Nam Keana Baking ...",no_brand,no_origin,no_type,"Da mụn trứng cá, Mọi loại da, Da hỗn hợp, Chàm...",3,bột rửa mặt sửa rửa mặt cho nam keana baking s...,80311948_21008859889.jpg,0.200048,"Sửa Rửa Mặt, Bột Rửa Mặt Cho Nam Keana Baking ..."
1748,5.0,22,180000.0,1748,Sữa rửa mặt Hemia chính hãngSạch sâukiềm dầu,Hemia,Hàn Quốc,dạng xịt,no_skin,2,sữa rửa mặt hemia hàn quốc tinh_thể bạc_hà dưỡ...,550791597_14932377810.jpg,0.200068,Sữa rửa mặt Hemia chính hãngSạch sâukiềm dầu [...
164,4.6,99,13000.0,164,Sữa rửa mặt Heyxi Sữa rửa mặt nha đam sạch sâu...,no_brand,Trung Quốc,no_type,Mọi loại da,17,sữa rửa mặt lô_hội heyxi sữa rửa mặt làm sạch ...,432265479_11040592494.jpg,0.184343,Sữa rửa mặt Heyxi Sữa rửa mặt nha đam sạch sâu...
208,4.9,3600,114000.0,208,Sữa Rửa Mặt Dành Cho Nam Ice Mud BLUEMAN - Là...,BLUEMAN,Trung Quốc,dạng lỏng,"Dầu, mọi loại da",1031,sữa rửa mặt dành cho nam ice mud blueman làm s...,266316857_5342127538.mp4,0.210321,Sữa Rửa Mặt Dành Cho Nam Ice Mud BLUEMAN - Là...
52,4.9,8400,179000.0,52,Sữa Rửa Mặt Cho Nam Skin&Dr Than Hoạt Tính 100...,Skin&Dr\t,Việt Nam,no_type,Da hỗn hợp,3051,sữa rửa mặt cho nam skin dr than hoạt_tính 10 ...,21080428_7821184960.mp4,0.232311,Sữa Rửa Mặt Cho Nam Skin&Dr Than Hoạt Tính 100...
312,4.9,65,115000.0,312,"Sữa Rửa Mặt Simple Kiềm Dầu, Ngừa Mụn Cho Da M...",simple,BA LAN,dạng sánh,"Da mụn trứng cá, Nhạy cảm",16,loại da phù_hợp thích_hợp cho da dầu mụn nhạy_...,714931975_17581688647.jpg,0.196247,"Sữa Rửa Mặt Simple Kiềm Dầu, Ngừa Mụn Cho Da M..."
1624,4.9,258,215000.0,1624,(Cam Kết Chính Hãng-Date mới nhất) Sữa Rửa Mặt...,Neutrogena,Canada,no_type,"Dầu, Da mụn",78,sữa rửa mặt oil fre acne wash dành cho da mụn ...,109730201_4836970479.jpg,0.197045,(Cam Kết Chính Hãng-Date mới nhất) Sữa Rửa Mặt...
305,4.7,92,25000.0,305,"Sữa Rửa Mặt COSRX Làm giảm mụn ,Kiềm Dầu 150ml",no_brand,no_origin,no_type,no_skin,31,sữa rửa mặt dạng gel cosrx làm giảm mụn kiềm d...,492888606_14735725194.jpg,0.188387,"Sữa Rửa Mặt COSRX Làm giảm mụn ,Kiềm Dầu 150ml..."
1774,4.7,105,11000.0,1774,Sữa Rửa Mặt Dưỡng Ẩm Sâu Kiềm Dầu Hỗ trợ giảm ...,no_brand,no_origin,no_type,Mọi loại da,32,tên sản_phẩm sữa rửa mặt quy_cách sản_phẩm 60 ...,779446622_20228384074.jpg,0.188426,Sữa Rửa Mặt Dưỡng Ẩm Sâu Kiềm Dầu Hỗ trợ giảm ...

In [130]:
male_face_clean = result_search["product_name"].tolist()
male_face_clean

['Sữa Rửa Mặt Kiềm Dầu, Sữa Rửa Mặt Tạo Bọt Cho Da Dầu Bạc Hà  - Đầu cọ sillicon sạch gấp 10 lần',
 'Sửa Rửa Mặt, Bột Rửa Mặt Cho Nam Keana Baking Soda Scrub Wash 100g Nhật Bản',
 'Sữa rửa mặt Hemia chính hãngSạch sâukiềm dầu',
 'Sữa rửa mặt Heyxi Sữa rửa mặt nha đam sạch sâu kiềm dầu dưỡng ẩm HSRM2',
 'Sữa Rửa Mặt Dành Cho Nam  Ice Mud BLUEMAN - Làm Sạch Dầu Và Bã Nhờn 170ml',
 'Sữa Rửa Mặt Cho Nam Skin&Dr Than Hoạt Tính 100g - Trắng da kiềm dầu',
 'Sữa Rửa Mặt Simple Kiềm Dầu, Ngừa Mụn Cho Da Mụn 150ml  - Sản phẩm chính hãng',
 '(Cam Kết Chính Hãng-Date mới nhất) Sữa Rửa Mặt Dành Cho Da Mụn Neutrogena Oil-Free Acne Wash 269 ml',
 'Sữa Rửa Mặt COSRX Làm giảm mụn ,Kiềm Dầu 150ml',
 'Sữa Rửa Mặt Dưỡng Ẩm Sâu Kiềm Dầu Hỗ trợ giảm mụn 60g GYLMZ937']

In [131]:
query = "Sữa rửa mặt kiềm dầu cho nam"
result_search = search_products_embedding(query, top_n=10, model_name="bi-encoder")
print(f"Kết quả tìm kiếm cho '{query}':")
male_face_clean = result_search["product_name"].tolist()
male_face_clean

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Kết quả tìm kiếm cho 'Sữa rửa mặt kiềm dầu cho nam':

['Sữa Rửa Mặt Dành Cho Nam  Ice Mud BLUEMAN - Làm Sạch Dầu Và Bã Nhờn 170ml',
 'Sữa Rửa Mặt Dành Cho Nam Sukin For Men Facial Cleanser 225ml',
 'Sữa rửa mặt nam RHYS MAN hương dừa Rhys Coconut Fresh 100ml',
 'Sữa rửa mặt nam RHYS MAN hương dừa thơm mát Rhys Coconut Fresh 100ml',
 'Sữa rửa mặt nam 30Shine phân phối chính hãng Skin&dr Tràm trà 80g cho da mụn, da dầu, dưỡng ẩm trắng da',
 'Sữa rửa mặt nam 30Shine phân phối chính hãng Skin&dr Tràm trà 80g cho da mụn, da dầu, dưỡng ẩm trắng da',
 'Sữa Rửa Mặt Cho Nam Skin&Dr Than Hoạt Tính 100g - Trắng da kiềm dầu',
 'Sữa rửa mặt nam RHYS MAN Rhys Coconut Fresh hương dừa thơm mát 100ml',
 "Sữa rửa mặt Paula's Choice Skin Balancing Oil-Reducing Cleanser (237mL)",
 'Sữa rửa mặt nam RHYS MAN hương dừa Rhys Coconut Fresh 100ml']