In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import linear_kernel
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

## 1. Load product data

In [2]:
df_product = pd.read_csv("../data/data_product_combine.csv")
display(df_product)

,avg_star,num_sold_time,price,product_id,product_name,brand,origin,type,skin_kind,num_rating,processed_description,image_path,popularity_score,combined_text
0,4.8,185700,99000.0,0,Sữa rửa mặt Simple lành tính sạch thoáng - cho...,simple,no_origin,no_type,no_skin,66840,ưu_điểm nổi_trội sữa rửa mặt simple lành_tính ...,111138057_8587034871.jpg,0.988000,Sữa rửa mặt Simple lành tính sạch thoáng - cho...
1,4.8,102600,99000.0,1,Sữa rửa mặt Simple giúp kiềm dầu và ngừa mụn h...,simple,no_origin,no_type,no_skin,36552,ưu_điểm nổi_trội sữa rửa mặt simple giúp kiềm ...,111138057_8287055694.jpg,0.673624,Sữa rửa mặt Simple giúp kiềm dầu và ngừa mụn h...
2,4.9,8100,244000.0,2,Sữa rửa mặt nam 30Shine phân phối chính hãng S...,Skin&Dr\t,Việt Nam,dạng kem,no_skin,2644,sữa rửa mặt nam skin dr tràm trà 80 g cho da m...,21080428_9335942418.mp4,0.323721,Sữa rửa mặt nam 30Shine phân phối chính hãng S...
3,4.9,3600,119000.0,3,Sữa rửa mặt nam RHYS MAN Rhys Coconut Fresh hư...,RHYS MAN,Việt Nam,dạng sánh,Da hỗn hợp,180,chính hãng sữa rửa mặt nam rhys man rhys cocon...,758111427_19601743242.mp4,0.304232,Sữa rửa mặt nam RHYS MAN Rhys Coconut Fresh hư...
4,4.8,26300,9900.0,4,Sữa Rửa Mặt Senana Lấy Sạch Bụi Bẩn Giúp Da T...,no_brand,no_origin,no_type,no_skin,6312,sỉ tốt 13 k c bao giá sl toàn_quốc ngại j khôn...,107632788_3330988133.jpg,0.377700,Sữa Rửa Mặt Senana Lấy Sạch Bụi Bẩn Giúp Da T...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2239,5.0,872,82000.0,2239,Sữa rửa mặt Kose Softymo Nhật Bản 220g,KOSÉ,no_origin,no_type,no_skin,270,sữa rửa mặt kose nhật bản best của best luôn a...,294293046_5445658669.jpg,0.303156,Sữa rửa mặt Kose Softymo Nhật Bản 220g [BRAND]...
2240,5.0,43,205000.0,2240,Sữa rửa mặt La Roche-Posay Effaclar chuyên dàn...,La Roche-Posay,Pháp,dạng gel,"Da mụn trứng cá, Da hỗn hợp, Dầu, Nhạy cảm",12,sữa rửa mặt la efaclar foaming gel sẽ giúp ngă...,97333460_10761076591.jpg,0.300152,Sữa rửa mặt La Roche-Posay Effaclar chuyên dàn...
2241,4.9,823,75000.0,2241,Sữa rửa mặt Kose Softymo Nhật Bản 220g,no_brand,no_origin,no_type,no_skin,218,sữa rửa mặt kose softymo là sản_phẩm sữa rửa m...,315629668_3455178555.jpg,0.296868,Sữa rửa mặt Kose Softymo Nhật Bản 220g [BRAND]...
2242,5.0,1000,79000.0,2242,Sữa Rửa Mặt Làm Sáng Da Reihaku Hatomugi Facia...,HATOMUGI,Nhật Bản,no_type,no_skin,439,thương_hiệu reihaku hatomugi xuất_xứ nhật bản ...,258099521_6677227750.jpg,0.304006,Sữa Rửa Mặt Làm Sáng Da Reihaku Hatomugi Facia...
2243,4.9,186,30000.0,2243,Sữa Rửa Mặt Bơ Aron Thái Lan 210g dưỡng ẩm và ...,no_brand,no_origin,no_type,no_skin,35,sữa rửa mặt bơ aron thái lan 210 g dưỡng ẩm và...,40662254_15079529213.jpg,0.294606,Sữa Rửa Mặt Bơ Aron Thái Lan 210g dưỡng ẩm và ...

In [3]:
df_product.columns

Index(['avg_star', 'num_sold_time', 'price', 'product_id', 'product_name',
       'brand', 'origin', 'type', 'skin_kind', 'num_rating',
       'processed_description', 'image_path', 'popularity_score',
       'combined_text'],
      dtype='object')

## TF-IDF

**TF-IDF** (viết tắt của Term Frequency-Inverse Document Frequency) là một kỹ thuật thống kê dạng số dùng để đánh giá tầm quan trọng của một từ trong một tài liệu hoặc một văn bản trong một tập hợp các tài liệu (corpus). Giá trị TF-IDF càng cao thì độ quan trọng của từ đó càng lớn trong tài liệu và trong cả tập hợp tài liệu.

In [3]:
tf = TfidfVectorizer(analyzer="word")
tfidf_matrix = tf.fit_transform(df_product["combined_text"])
tfidf_matrix  # la sparse matrix

<2244x10604 sparse matrix of type '<class 'numpy.float64'>'
	with 324624 stored elements in Compressed Sparse Row format>

In [4]:
tfidf_matrix.shape

(2244, 10604)

In [5]:
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
cosine_sim

array([[1.        , 0.86255579, 0.16297268, ..., 0.19061156, 0.18217464,
        0.18487124],
       [0.86255579, 1.        , 0.17539769, ..., 0.20054225, 0.19160009,
        0.17756289],
       [0.16297268, 0.17539769, 1.        , ..., 0.15743214, 0.15593822,
        0.13342997],
       ...,
       [0.19061156, 0.20054225, 0.15743214, ..., 1.        , 0.23010215,
        0.23670292],
       [0.18217464, 0.19160009, 0.15593822, ..., 0.23010215, 1.        ,
        0.17223299],
       [0.18487124, 0.17756289, 0.13342997, ..., 0.23670292, 0.17223299,
        1.        ]])

## AITeamVN/Vietnamese-Embedding

In [6]:
import torch
from sentence_transformers import SentenceTransformer

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

/home/daniel/anaconda3/envs/face_clean/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Using device: cuda

In [7]:
text_combine = df_product["combined_text"].values.tolist()

In [9]:
# Tải mô hình Vietnamese_Embedding
vietnamese_embedding = SentenceTransformer(
    "AITeamVN/Vietnamese_Embedding", cache_folder="../models"
)
vietnamese_embedding.max_seq_length = 1024
vietnamese_embedding.to(device)

# Tải mô hình Vietnamese_bi_encoder
vietnamese_bi_encoder = SentenceTransformer(
    "bkai-foundation-models/vietnamese-bi-encoder", cache_folder="../models"
)
vietnamese_bi_encoder.max_seq_length = 256
vietnamese_bi_encoder.to(device)

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False}) with Transformer model: RobertaModel
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
)

In [ ]:
# # Encode dữ liệu mô tả sản phẩm
# encoded_descriptions = vietnamese_embedding.encode(product_descriptions,
#                                                    show_progress_bar=True,
#                                                    batch_size=64,
#                                                    convert_to_numpy=True,
#                                                    device=device)

# # Luu lai ket qua
# np.save('/kaggle/working/vietnamese_embedding.npy', encoded_descriptions)

# # giai phong bo nho Vram
# vietnamese_embedding.to("cpu")
# torch.cuda.empty_cache()

In [8]:
vie_embed = np.load("../embeddings/vietnamese_embedding.npy")
print(vie_embed.shape)
vie_embed_cosine_sim = linear_kernel(vie_embed, vie_embed)
vie_embed_cosine_sim

(2244, 1024)

array([[0.99999976, 0.77119064, 0.42959487, ..., 0.48645732, 0.5059805 ,
        0.47021967],
       [0.77119064, 1.        , 0.4423456 , ..., 0.5088983 , 0.4706413 ,
        0.47992554],
       [0.42959487, 0.4423456 , 1.0000002 , ..., 0.39891997, 0.38103262,
        0.3925349 ],
       ...,
       [0.48645732, 0.5088983 , 0.39891997, ..., 0.9999999 , 0.5295361 ,
        0.48498666],
       [0.5059805 , 0.4706413 , 0.38103262, ..., 0.5295361 , 0.99999994,
        0.56553054],
       [0.47021967, 0.47992554, 0.3925349 , ..., 0.48498666, 0.56553054,
        1.0000002 ]], dtype=float32)

## BKAI-Foundation-Models/Vietnamese-bi-encoder

In [ ]:
# # Encode dữ liệu mô tả sản phẩm
# vie_bi_encode = vietnamese_bi_encoder.encode(product_descriptions,
#                                                    show_progress_bar=True,
#                                                    batch_size=64,
#                                                    convert_to_numpy=True,
#                                                    device=device)

# # Lu lai ket qua
# np.save('vie_bi_encode_embedding.npy', vie_bi_encode)

# # giai phong bo nho Vram
# vietnamese_bi_encoder.to("cpu")
# torch.cuda.empty_cache()

In [9]:
from sklearn.preprocessing import normalize

vie_bi_encoder_embed = np.load("../embeddings/vie_bi_encode_embedding.npy")
print(vie_bi_encoder_embed.shape)
vie_bi_encoder_cosine_sim = linear_kernel(
    normalize(vie_bi_encoder_embed), normalize(vie_bi_encoder_embed)
)
vie_bi_encoder_cosine_sim

(2244, 768)

array([[1.0000001 , 0.746165  , 0.37766963, ..., 0.47660193, 0.3045453 ,
        0.3479591 ],
       [0.746165  , 0.9999999 , 0.49647978, ..., 0.46904504, 0.3282598 ,
        0.3645295 ],
       [0.37766963, 0.49647978, 0.99999976, ..., 0.3370647 , 0.3232962 ,
        0.31455487],
       ...,
       [0.47660193, 0.46904504, 0.3370647 , ..., 1.        , 0.4376124 ,
        0.33865833],
       [0.3045453 , 0.3282598 , 0.3232962 , ..., 0.4376124 , 1.0000001 ,
        0.44169387],
       [0.3479591 , 0.3645295 , 0.31455487, ..., 0.33865833, 0.44169387,
        0.99999994]], dtype=float32)

## Recommend

In [10]:
# Anh xa product_id -> index, voi value la index cua df_product
id_prod = df_product["product_id"]
indices = pd.Series(df_product.index, index=id_prod)

In [11]:
id_name_dict = df_product.set_index("product_id")[
    "product_name"
].to_dict()  # Dictionary anh xa product_id -> product_name
name_id_dict = df_product.set_index("product_name")[
    "product_id"
].to_dict()  # Dictionary anh xa product_name -> product_id

In [36]:
print(id_name_dict[999])
print(
    name_id_dict["(CHÍNH HÃNG - ĐÀI LOAN) SỮA RỬA MẶT NARUKO CÁC LOẠI TUÝP 120G/120ML"]
)

(CHÍNH HÃNG - ĐÀI LOAN) SỮA RỬA MẶT NARUKO CÁC LOẠI TUÝP 120G/120ML
999

In [12]:
df_purchase = pd.read_csv("../data/data_purchase.csv")

In [13]:
display(df_purchase.head(20))

    user_id  product_id             cmt_date
0    295796        2221  2022-12-21 06:46:28
1    295796        1886  2022-11-18 06:39:16
2    295796        1951  2022-09-19 07:23:34
3    290595        1768  2022-12-13 13:23:02
4    290595        1814  2022-11-12 12:03:30
5    290595        1763  2022-05-13 09:39:35
6    289116        1711  2021-10-01 04:15:25
7    289116        1808  2021-09-20 04:03:43
8    289116        2092  2020-04-07 12:20:56
9    285040        2191  2022-03-30 12:26:07
10   285040        1616  2021-06-30 11:59:25
11   285040        1793  2021-05-10 17:31:26
12   283596        1787  2021-07-19 12:41:55
13   283596        2222  2021-07-10 10:28:48
14   283596        1599  2021-07-10 10:28:48
15   283563        1599  2022-12-30 03:42:58
16   283563        2222  2022-08-20 07:35:44
17   283563        2135  2021-09-17 19:11:15
18   282691        2061  2022-09-10 09:07:49
19   282691        2051  2022-08-05 07:26:42

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity


def content_base_recommendation(product_id, cosine_similarity_matrix):

    idx = indices[product_id]  # Lấy index của sản phẩm dựa trên product_id
    sim_scores = list(enumerate(cosine_similarity_matrix[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:101]  # lay 100 san pham, bo qua san pham cua chinh no
    df_indices = [i[0] for i in sim_scores]  # tra ve danh sach index procuct_id

    popularity_scores = df_product.loc[df_indices, "popularity_score"]
    temp_df = pd.DataFrame(sim_scores, columns=["index", "score"])
    temp_df.index = temp_df["index"]
    temp_df.drop(columns=["index"], axis=1, inplace=True)

    score = temp_df["score"] * 0.7 + popularity_scores * 0.3
    score = score.sort_values(ascending=False)
    product_indices = score.index[:10]

    return product_indices


result = content_base_recommendation(
    name_id_dict[
        "Sữa rửa mặt Simple lành tính sạch thoáng - cho da nhạy cảm 150ml [CHÍNH HÃNG ĐỘC QUYỀN] [DIỆN MẠO MỚI]"
    ],
    vie_embed_cosine_sim,
)


for prod_id in result.to_list():
    print(id_name_dict[prod_id])

SỮA RỬA MẶT SIMPLE GIÚP DƯỠNG ẨM CHO DA TRÔNG KHỎE VÀ MỊN MÀNG 150ML [CHÍNH HÃNG ĐỘC QUYỀN] [DIỆN MẠO MỚI]
Sữa rửa mặt Simple giúp kiềm dầu và ngừa mụn hiệu quả - cho da dầu mụn 150ml [CHÍNH HÃNG ĐỘC QUYỀN] [DIỆN MẠO MỚI]
Sữa rửa mặt Simple giúp da sạch thoáng & không chứa xà phòng 150ml
Sữa rửa mặt Simple dịu nhẹ giúp da sạch thoáng, không chứa xà phòng 150ml
Sữa rửa mặt Simple giúp da sạch thoáng & không chứa xà phòng 150ml
Sữa Rửa Mặt Simple Dành Cho Da Thường,Da Mụn 150ml
[Chính hãng] Sữa rửa mặt Simple giúp da sạch thoáng & không chứa xà phòng 150ml
Combo Simple Tẩy trang 200ml + Sữa rửa mặt 150ml + Nước hoa hồng 200ml cho da sạch khỏe đàn hồi [CHÍNH HÃNG ĐỘC QUYỀN]
[Bạn mới nhập COSHBM -50% đơn 0Đ] [Loại 150ml] Sữa Rửa Mặt Simple Gel Kind To Skin Refreshing Facial Wash Gel
Sữa rửa mặt Simple giúp kiềm dầu và ngừa mụn hiệu quả - cho da mụn nhạy cảm 150ml

In [34]:
df_product[df_product["product_id"].isin(result)]

,avg_star,num_sold_time,price,product_id,product_name,brand,origin,type,skin_kind,num_rating,processed_description,image_path,popularity_score,combined_text
1,4.8,102600,99000.0,1,Sữa rửa mặt Simple giúp kiềm dầu và ngừa mụn h...,simple,no_origin,no_type,no_skin,36552,ưu_điểm nổi_trội sữa rửa mặt simple giúp kiềm ...,111138057_8287055694.jpg,0.673624,Sữa rửa mặt Simple giúp kiềm dầu và ngừa mụn h...
122,4.9,1200,89000.0,122,Sữa rửa mặt Simple giúp da sạch thoáng & không...,simple,Poland,khác,Mọi loại da,159,simple là nhãn_hiệu chăm_sóc da số 1 anh quốc ...,198891602_15406313170.jpg,0.297707,Sữa rửa mặt Simple giúp da sạch thoáng & không...
159,4.9,17000,213000.0,159,Combo Simple Tẩy trang 200ml + Sữa rửa mặt 150...,simple,no_origin,no_type,no_skin,6123,ưu_điểm nổi_trội 1 nước tẩy_trang simple micel...,111138057_16760174157.jpg,0.358094,Combo Simple Tẩy trang 200ml + Sữa rửa mặt 150...
204,4.8,31300,98000.0,204,SỮA RỬA MẶT SIMPLE GIÚP DƯỠNG ẨM CHO DA TRÔNG ...,simple,no_origin,no_type,no_skin,11036,ưu_điểm nổi_trội sữa rửa mặt simple sạch sâu c...,111138057_9587055242.jpg,0.405298,SỮA RỬA MẶT SIMPLE GIÚP DƯỠNG ẨM CHO DA TRÔNG ...
319,4.9,40800,109000.0,319,[Bạn mới nhập COSHBM -50% đơn 0Đ] [Loại 150ml]...,no_brand,no_origin,no_type,no_skin,18242,sữa rửa mặt simple gel freshing 150 ml dịu nhẹ...,411521204_10307391942.mp4,0.458439,[Bạn mới nhập COSHBM -50% đơn 0Đ] [Loại 150ml]...
587,4.8,1900,73000.0,587,Sữa rửa mặt Simple dịu nhẹ giúp da sạch thoáng...,simple,Ba Lan,dạng sánh,Mọi loại da,411,sữa rửa mặt simple dịu nhẹ giúp da sạch thoáng...,403116788_15321646693.mp4,0.294346,Sữa rửa mặt Simple dịu nhẹ giúp da sạch thoáng...
642,5.0,23,115000.0,642,Sữa rửa mặt Simple giúp kiềm dầu và ngừa mụn h...,simple,no_origin,no_type,"Da mụn trứng cá, Nhạy cảm",7,ưu_điểm nổi_trội sữa rửa mặt simple giúp kiềm ...,393478450_21526436402.jpg,0.300083,Sữa rửa mặt Simple giúp kiềm dầu và ngừa mụn h...
937,4.9,303,95000.0,937,[Chính hãng] Sữa rửa mặt Simple giúp da sạch t...,simple,Anh,dạng sánh,no_skin,47,ưu_điểm nổi_trội sữa rửa mặt simple giúp da sạ...,216645583_17139864381.jpg,0.294956,[Chính hãng] Sữa rửa mặt Simple giúp da sạch t...
1484,5.0,83,115000.0,1484,Sữa rửa mặt Simple giúp da sạch thoáng & không...,simple,Anh,dạng lỏng,Mọi loại da,32,thông_tin thương_hiệu là nhãn_hiệu chăm_sóc da...,714931975_15868759418.jpg,0.300319,Sữa rửa mặt Simple giúp da sạch thoáng & không...
2223,5.0,39,102000.0,2223,"Sữa Rửa Mặt Simple Dành Cho Da Thường,Da Mụn 1...",simple,no_origin,dạng lỏng,"Da mụn trứng cá, Mọi loại da, Da hỗn hợp, Bình...",6,ưu_điểm nổi_trội sữa rửa mặt simple giúp da sạ...,239088754_21614700428.jpg,0.300123,"Sữa Rửa Mặt Simple Dành Cho Da Thường,Da Mụn 1..."

## Evaluation

In [16]:
df_purchase

       user_id  product_id             cmt_date
0       295796        2221  2022-12-21 06:46:28
1       295796        1886  2022-11-18 06:39:16
2       295796        1951  2022-09-19 07:23:34
3       290595        1768  2022-12-13 13:23:02
4       290595        1814  2022-11-12 12:03:30
...        ...         ...                  ...
12758      254         587  2023-01-01 14:03:31
12759      254           0  2022-08-17 03:59:49
12760       40         159  2022-12-20 13:03:12
12761       40           1  2022-12-20 13:03:12
12762       40           0  2022-12-20 13:03:12

[12763 rows x 3 columns]

In [17]:
# split data into train, test, val
train_index = [i for i in range(2, 12763, 3)]
test_index = [i for i in range(1, 12763, 3)]
val_index = [i for i in range(0, 12763, 3)]

In [19]:
df_purchase.iloc[train_index, :]["user_id"].value_counts()

13780     4
22708     4
176302    4
112935    3
12643     3
         ..
113907    1
113888    1
113725    1
113701    1
40        1
Name: user_id, Length: 3952, dtype: int64

In [20]:
df_purchase.iloc[val_index, :]["user_id"].value_counts()

176302    4
22708     4
101438    3
57610     3
13487     3
         ..
113907    1
113888    1
113725    1
113701    1
40        1
Name: user_id, Length: 3952, dtype: int64

In [21]:
df_purchase.iloc[test_index, :]["user_id"].value_counts()

176302    4
22708     4
15488     4
13780     4
5935      3
         ..
114149    1
114090    1
113907    1
113888    1
40        1
Name: user_id, Length: 3952, dtype: int64

In [44]:
df_purchase["user_id"].value_counts()

176302    12
22708     12
13780     11
15488     10
101438     9
          ..
109632     3
109558     3
109532     3
109451     3
40         3
Name: user_id, Length: 3952, dtype: int64

In [45]:
print(len(train_index), len(test_index), len(val_index))

4254 4254 4255

In [22]:
def PtopK(y_true, y_pred):
    """
    Precision at K: Tính tỷ lệ phần trăm của các mục đúng trong top K dự đoán.
    """
    if y_true in y_pred:
        return 1 / len(y_pred)
    else:
        return 0


def RtopK(y_true, y_pred):
    """
    Recall at K: Tính tỷ lệ phần trăm của các mục đúng được tìm thấy trong top K dự đoán.
    """
    if y_true in y_pred:
        return 1
    else:
        return 0


def MRR(y_true, y_pred):
    """
    Mean Reciprocal Rank (MRR): Tính trung bình của các hạng mục đúng trong top K dự đoán.
    """
    if y_true not in y_pred:
        return 0

    rank = 0
    for index, value in enumerate(y_pred):
        if value == y_true:
            rank = 1 / (index + 1)
            break

    return rank


def NDCG(y_true, y_pred, k=None):
    """
    Normalized Discounted Cumulative Gain (NDCG): Đo lường chất lượng của các dự đoán xếp hạng.
    """
    if y_true not in y_pred:
        return 0.0

    true_index = y_pred.index(y_true)
    ideal_sorted = sorted(y_pred, reverse=True)
    ideal_index = ideal_sorted.index(y_true)

    dcg = 1.0 / np.log2(true_index + 2)
    idcg = 1.0 / np.log2(ideal_index + 2)

    ndcg = dcg / idcg

    if k is not None:
        ideal_sorted = ideal_sorted[:k]
        y_pred = y_pred[:k]
        true_index = y_pred.index(y_true)
        ideal_index = ideal_sorted.index(y_true)
        dcg = 1.0 / np.log2(true_index + 2)
        idcg = 1.0 / np.log2(ideal_index + 2)
        ndcg = dcg / idcg

    return ndcg


def calculate_mean(numbers):
    if not numbers:
        return 0.0
    return sum(numbers) / len(numbers)

In [31]:
cosine_mxs = {
    "BKAI/Vietnamese-bi-encoder": vie_bi_encoder_cosine_sim,
    "AITeamVN/Vietnamese-Embedding": vie_embed_cosine_sim,
    "TF-IDF": cosine_sim,
}

for name, embedding in cosine_mxs.items():
    print("-------------------------------------")
    print(f"Evaluating model: {name}")
    rtopk_val = []
    rtopk_test = []
    ptopk_val = []
    ptopk_test = []
    mrr_val = []
    mrr_test = []
    ndcg_val = []
    ndcg_test = []

    for user in df_purchase["user_id"].unique():
        temp = df_purchase[df_purchase["user_id"] == user]
        x_val = temp.iloc[2, 1]  # index product_id for train
        y_val = temp.iloc[1, 1]  # index product_id for val
        y_val_pred = content_base_recommendation(x_val, embedding).tolist()
        rtopk_val.append(RtopK(y_val, y_val_pred))
        ptopk_val.append(PtopK(y_val, y_val_pred))
        mrr_val.append(MRR(y_val, y_val_pred))
        ndcg_val.append(NDCG(y_val, y_val_pred, 10))

        x_test = temp.iloc[1, 1]
        y_test = temp.iloc[0, 1]
        y_test_pred = content_base_recommendation(x_test, embedding).tolist()
        rtopk_test.append(RtopK(y_test, y_test_pred))
        ptopk_test.append(PtopK(y_test, y_test_pred))
        mrr_test.append(MRR(y_test, y_test_pred))
        ndcg_test.append(NDCG(y_test, y_test_pred, 10))

    print("rtopk val:", calculate_mean(rtopk_val))
    print("rtopk test:", calculate_mean(rtopk_test))
    print("ptopk val:", calculate_mean(ptopk_val))
    print("ptopk test:", calculate_mean(ptopk_test))
    print("mrr val:", calculate_mean(mrr_val))
    print("mrr test:", calculate_mean(mrr_test))
    print("ndcg val:", calculate_mean(ndcg_val))
    print("ndcg test:", calculate_mean(ndcg_test))

-------------------------------------
Evaluating model: BKAI/Vietnamese-bi-encoder
rtopk val: 0.11690283400809717
rtopk test: 0.14271255060728744
ptopk val: 0.011690283400809815
ptopk test: 0.014271255060728879
mrr val: 0.053371810937600336
mrr test: 0.0656530147484094
ndcg val: 0.20050552372614522
ndcg test: 0.2446298519787927
-------------------------------------
Evaluating model: AITeamVN/Vietnamese-Embedding
rtopk val: 0.12297570850202429
rtopk test: 0.15814777327935223
ptopk val: 0.012297570850202536
ptopk test: 0.01581477732793538
mrr val: 0.055818432298695396
mrr test: 0.07164947625473926
ndcg val: 0.20667068240602757
ndcg test: 0.2656163381850873
-------------------------------------
Evaluating model: TF-IDF
rtopk val: 0.11513157894736842
rtopk test: 0.14752024291497975
ptopk val: 0.011513157894736937
ptopk test: 0.014752024291498116
mrr val: 0.05447101327035539
mrr test: 0.07065500289184494
ndcg val: 0.19347047853934674
ndcg test: 0.24444354880318805

## Parameter finetuning

In [32]:
score = [0.1 * i for i in range(1, 11)]
score

[0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0]

In [26]:
def recommendation(product_id, src_score, cosine_similarity_matrix):

    idx = indices[product_id]  # Lấy index của sản phẩm dựa trên product_id
    sim_scores = list(enumerate(cosine_similarity_matrix[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:101]  # lay 100 san pham, bo qua san pham cua chinh no
    df_indices = [i[0] for i in sim_scores]  # tra ve danh sach index procuct_id

    popularity_scores = df_product.loc[df_indices, "popularity_score"]
    temp_df = pd.DataFrame(sim_scores, columns=["index", "score"])
    temp_df.index = temp_df["index"]
    temp_df.drop(columns=["index"], axis=1, inplace=True)

    score = temp_df["score"] * src_score + popularity_scores * (1 - src_score)
    score = score.sort_values(ascending=False)
    product_indices = score.index[:10]

    return product_indices

In [35]:
from tqdm import tqdm

index = 0
df = pd.DataFrame(
    columns=[
        "score_weight",
        "popular_weight",
        "rtopk_val",
        "rtopk_test",
        "ptopk_val",
        "ptopk_test",
        "mrr_val",
        "mrr_test",
        "ndcg_val",
        "ndcg_test",
    ]
)

for scr in tqdm(score):
    rtop_val = []
    rtop_test = []
    ptop_val = []
    ptop_test = []
    mrr_val = []
    mrr_test = []
    ndcg_val = []
    ndcg_test = []

    for user in df_purchase["user_id"].unique():
        temp = df_purchase[df_purchase["user_id"] == user]
        x_val = temp.iloc[2, 1]
        y_val = temp.iloc[1, 1]
        y_val_pred = recommendation(x_val, scr, vie_embed_cosine_sim).tolist()
        rtopk_val.append(RtopK(y_val, y_val_pred))
        ptopk_val.append(PtopK(y_val, y_val_pred))
        mrr_val.append(MRR(y_val, y_val_pred))
        ndcg_val.append(NDCG(y_val, y_val_pred, 10))

        x_test = temp.iloc[1, 1]
        y_test = temp.iloc[0, 1]
        y_test_pred = recommendation(x_test, scr, vie_embed_cosine_sim).tolist()
        rtopk_test.append(RtopK(y_test, y_test_pred))
        ptopk_test.append(PtopK(y_test, y_test_pred))
        mrr_test.append(MRR(y_test, y_test_pred))
        ndcg_test.append(NDCG(y_test, y_test_pred, 10))

    dict_temp = {
        "score_weight": scr,
        "popular_weight": 1 - scr,
        "rtopk_val": calculate_mean(rtopk_val),
        "rtopk_test": calculate_mean(rtopk_test),
        "ptopk_val": calculate_mean(ptopk_val),
        "ptopk_test": calculate_mean(ptopk_test),
        "mrr_val": calculate_mean(mrr_val),
        "mrr_test": calculate_mean(mrr_test),
        "ndcg_val": calculate_mean(ndcg_val),
        "ndcg_test": calculate_mean(ndcg_test),
    }

    df = pd.concat([df, pd.DataFrame(dict_temp, index=[index])], ignore_index=True)
    index += 1

100%|██████████| 10/10 [03:04<00:00, 18.40s/it]

In [36]:
df

,score_weight,popular_weight,rtopk_val,rtopk_test,ptopk_val,ptopk_test,mrr_val,mrr_test,ndcg_val,ndcg_test
0,0.1,0.9,0.150936,0.180162,0.015094,0.018016,0.074804,0.080666,0.280043,0.307259
1,0.2,0.8,0.160931,0.190030,0.016093,0.019003,0.075590,0.086999,0.281262,0.320351
2,0.3,0.7,0.163398,0.193952,0.016340,0.019395,0.072870,0.088491,0.271570,0.323220
3,0.4,0.6,0.161285,0.193067,0.016129,0.019307,0.068156,0.086293,0.250675,0.313201
4,0.5,0.5,0.158021,0.189735,0.015802,0.018974,0.064125,0.081667,0.235508,0.295114
5,0.6,0.4,0.154533,0.186307,0.015453,0.018631,0.059824,0.077211,0.222313,0.283571
6,0.7,0.3,0.150588,0.182787,0.015059,0.018279,0.055818,0.071649,0.206671,0.265616
7,0.8,0.2,0.146424,0.179009,0.014642,0.017901,0.052772,0.068876,0.192766,0.253195
8,0.9,0.1,0.142687,0.175278,0.014269,0.017528,0.050792,0.066792,0.184786,0.243372
9,1.0,0.0,0.139331,0.171927,0.013933,0.017193,0.048228,0.062866,0.176367,0.231659

In [37]:
df.sort_values(by=["ndcg_test"], ascending=False, inplace=True)
df

,score_weight,popular_weight,rtopk_val,rtopk_test,ptopk_val,ptopk_test,mrr_val,mrr_test,ndcg_val,ndcg_test
2,0.3,0.7,0.163398,0.193952,0.016340,0.019395,0.072870,0.088491,0.271570,0.323220
1,0.2,0.8,0.160931,0.190030,0.016093,0.019003,0.075590,0.086999,0.281262,0.320351
3,0.4,0.6,0.161285,0.193067,0.016129,0.019307,0.068156,0.086293,0.250675,0.313201
0,0.1,0.9,0.150936,0.180162,0.015094,0.018016,0.074804,0.080666,0.280043,0.307259
4,0.5,0.5,0.158021,0.189735,0.015802,0.018974,0.064125,0.081667,0.235508,0.295114
5,0.6,0.4,0.154533,0.186307,0.015453,0.018631,0.059824,0.077211,0.222313,0.283571
6,0.7,0.3,0.150588,0.182787,0.015059,0.018279,0.055818,0.071649,0.206671,0.265616
7,0.8,0.2,0.146424,0.179009,0.014642,0.017901,0.052772,0.068876,0.192766,0.253195
8,0.9,0.1,0.142687,0.175278,0.014269,0.017528,0.050792,0.066792,0.184786,0.243372
9,1.0,0.0,0.139331,0.171927,0.013933,0.017193,0.048228,0.062866,0.176367,0.231659

In [38]:
df.sort_values(by=["rtopk_test"], ascending=False, inplace=True)
df

,score_weight,popular_weight,rtopk_val,rtopk_test,ptopk_val,ptopk_test,mrr_val,mrr_test,ndcg_val,ndcg_test
2,0.3,0.7,0.163398,0.193952,0.016340,0.019395,0.072870,0.088491,0.271570,0.323220
3,0.4,0.6,0.161285,0.193067,0.016129,0.019307,0.068156,0.086293,0.250675,0.313201
1,0.2,0.8,0.160931,0.190030,0.016093,0.019003,0.075590,0.086999,0.281262,0.320351
4,0.5,0.5,0.158021,0.189735,0.015802,0.018974,0.064125,0.081667,0.235508,0.295114
5,0.6,0.4,0.154533,0.186307,0.015453,0.018631,0.059824,0.077211,0.222313,0.283571
6,0.7,0.3,0.150588,0.182787,0.015059,0.018279,0.055818,0.071649,0.206671,0.265616
0,0.1,0.9,0.150936,0.180162,0.015094,0.018016,0.074804,0.080666,0.280043,0.307259
7,0.8,0.2,0.146424,0.179009,0.014642,0.017901,0.052772,0.068876,0.192766,0.253195
8,0.9,0.1,0.142687,0.175278,0.014269,0.017528,0.050792,0.066792,0.184786,0.243372
9,1.0,0.0,0.139331,0.171927,0.013933,0.017193,0.048228,0.062866,0.176367,0.231659

In [39]:
df.sort_values(by=["mrr_test"], ascending=False, inplace=True)
df

,score_weight,popular_weight,rtopk_val,rtopk_test,ptopk_val,ptopk_test,mrr_val,mrr_test,ndcg_val,ndcg_test
2,0.3,0.7,0.163398,0.193952,0.016340,0.019395,0.072870,0.088491,0.271570,0.323220
1,0.2,0.8,0.160931,0.190030,0.016093,0.019003,0.075590,0.086999,0.281262,0.320351
3,0.4,0.6,0.161285,0.193067,0.016129,0.019307,0.068156,0.086293,0.250675,0.313201
4,0.5,0.5,0.158021,0.189735,0.015802,0.018974,0.064125,0.081667,0.235508,0.295114
0,0.1,0.9,0.150936,0.180162,0.015094,0.018016,0.074804,0.080666,0.280043,0.307259
5,0.6,0.4,0.154533,0.186307,0.015453,0.018631,0.059824,0.077211,0.222313,0.283571
6,0.7,0.3,0.150588,0.182787,0.015059,0.018279,0.055818,0.071649,0.206671,0.265616
7,0.8,0.2,0.146424,0.179009,0.014642,0.017901,0.052772,0.068876,0.192766,0.253195
8,0.9,0.1,0.142687,0.175278,0.014269,0.017528,0.050792,0.066792,0.184786,0.243372
9,1.0,0.0,0.139331,0.171927,0.013933,0.017193,0.048228,0.062866,0.176367,0.231659